- composer.lock
- config/app.php
Signed-off-by: Paco Orozco <paco@pacoorozco.info>
> refactor: Change Laravel IDE Helper to L5 code

- app/Console/Commands/SendKeysToHosts.php
- app/Events/Event.php
- app/Exceptions/Handler.php
- app/Host.php
- app/Hostgroup.php
- app/Http/Controllers/FileEntryController.php
- app/Http/Controllers/HostController.php
- app/Http/Controllers/HostgroupController.php
- app/Http/Controllers/RuleController.php
- app/Http/Controllers/SettingsController.php
- app/Http/Controllers/UsergroupController.php
- app/Http/Middleware/Authenticate.php
- app/Http/Middleware/RedirectIfAuthenticated.php
- app/Http/Middleware/VerifyCsrfToken.php
- app/Http/Requests/SettingsRequest.php
- app/Rule.php
- app/Usergroup.php
@pacoorozco requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/pacoorozco/ssham/
> Scrutinizer Auto-Fixes

- CHANGELOG.md
- docker/web/Dockerfile
> Fix web docker

- app/Host.php
- app/Hostgroup.php
- app/Http/Controllers/HomeController.php
- app/Http/Requests/SearchRequest.php
- app/User.php
- app/Usergroup.php
- composer.json
- composer.lock
- resources/lang/en/search/messages.php
- resources/lang/en/site.php
- resources/views/partials/navbar.blade.php
- resources/views/search.blade.php
- routes/web.php
> Add search feature

- .env.example
- CHANGELOG.md
- composer.lock
- config/trustedproxy.php
- package-lock.json
- package.json
/kind bug
resolves two vulnerabilities and add configuration to [Trusted Proxies](https://laravel.com/docs/6.x/requests#configuring-trusted-proxies)
See `config/trustedproxy.php` to configure  [Trusted Proxies](https://laravel.com/docs/6.x/requests#configuring-trusted-proxies)
No
**What else do we need to know?**
> Add trusted proxies and fix two vulnerabilites

- CHANGELOG.md
- composer.lock
- package-lock.json
- package.json
- tests/Feature/Http/Controllers/ControlRuleControllerTest.php
- tests/Feature/Http/Controllers/HostControllerTest.php
- tests/Feature/Http/Controllers/HostgroupControllerTest.php
- tests/Feature/Http/Controllers/KeyControllerTest.php
- tests/Feature/Http/Controllers/KeygroupControllerTest.php
- tests/Feature/Http/Controllers/SettingsControllerTest.php
- tests/Feature/Http/Controllers/UserControllerTest.php
Updating dependencies to fix some vulnerabilities.
> Update dependencies to fix some vulnerabilities

- CHANGELOG.md
- app/Helpers/Helper.php
- app/Http/Controllers/KeyController.php
- app/Key.php
- app/Traits/UsesUUID.php
/kind bug
There was some non-PSR-4 classes that were announced by `composer dump-autoload`.
> Fix some non PSR-4 classes

- .github/workflows/vuepress-deploy.yml
- .gitignore
- CHANGELOG.md
- composer.json
- docs/.vuepress/config.js
- docs/README.md
- package-lock.json
- package.json
/kind documentation
Add a project documentation site at [https://ssham.pacoorozco.info](https://ssham.pacoorozco.info)
> Add project documentation site

- CHANGELOG.md
- app/Console/Commands/SendKeysToHosts.php
- app/Host.php
- app/Hostgroup.php
- database/factories/KeyFactory.php
- phpunit.xml
- tests/Feature/Models/HostTest.php
> Fix issue 55: Keygroups error when the artisan job is executed

- .github/workflows/vuepress-deploy.yml
> Change the branch main instead of the old master

- app/Http/Controllers/HomeController.php
- app/Http/Controllers/SearchController.php
- app/Models/Activity.php
- app/Presenters/ActivityPresenter.php
- composer.json
- composer.lock
- config/activitylog.php
- resources/lang/en/activity/model.php
- resources/lang/en/site.php
- resources/views/dashboard/_latest_events.blade.php
- resources/views/dashboard/index.blade.php
- routes/web.php
resolves #85
No
Yes, `spatie/laravel-activitylog`
> Improve look & feel of the 'latest events' section on the homepage

- CHANGELOG.md
- app/Http/Kernel.php
- composer.json
- composer.lock
- config/cors.php
- config/session.php
/kind bug
resolves #92 
No
Yes, `fruitcake/laravel-cors`
> Add CORS support

- CHANGELOG.md
- app/Http/Requests/ControlRuleCreateRequest.php
> Fix issue #89

- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- composer.lock
Deprecate and remove PHP 7.4 support. 
Yes, minimum PHP version is 8.0
> Remove PHP <8.0 support

- app/Http/Controllers/HostController.php
- app/Http/Requests/HostCreateRequest.php
- app/Http/Requests/HostUpdateRequest.php
- app/Jobs/CreateHost.php
- app/Jobs/DeleteHost.php
- app/Jobs/UpdateHost.php
- app/Models/Host.php
- tests/Feature/Models/HostTest.php
- tests/Unit/HostTest.php
> Refactor to use Jobs in Host controller

- app/Exceptions/Handler.php
- composer.json
- composer.lock
Remove support of related #110 to merge latest changes (that are preparing the API but not implementing it)
> Remove laravel-json-api/laravel support

- CHANGELOG.md
- app/Http/Controllers/UserController.php
- app/Http/Requests/UserCreateRequest.php
- app/Http/Requests/UserUpdateRequest.php
- app/Jobs/ChangeUserPassword.php
- app/Jobs/CreateUser.php
- app/Jobs/UpdateUser.php
> Refactor User Controller to use Jobs.

- .travis.yml
Signed-off-by: pacoorozco <paco@pacoorozco.info>
/kind bug
resolves Code coverage generation in Travis
> Add XDEBUG variable to enable code coverage in Travis

- app/Exceptions/Handler.php
- app/Http/Requests/HostgroupCreateRequest.php
- app/Http/Requests/HostgroupUpdateRequest.php
- app/JsonApi/V1/Hostgroups/HostgroupRequest.php
- app/JsonApi/V1/Hostgroups/HostgroupSchema.php
- app/JsonApi/V1/Hosts/HostRequest.php
- app/JsonApi/V1/Hosts/HostSchema.php
- app/JsonApi/V1/Server.php
- app/Models/Hostgroup.php
- app/Policies/HostPolicy.php
- app/Policies/HostgroupPolicy.php
- app/Providers/AuthServiceProvider.php
- app/Providers/RouteServiceProvider.php
- composer.json
- composer.lock
- config/jsonapi.php
- routes/api.php
- tests/ApiTestCase.php
- tests/Feature/Http/Api/ApiHostgroupsTest.php
- tests/Feature/Http/Api/ApiHostsTest.php
- tests/Unit/Models/ControlRuleTest.php
- tests/Unit/Models/HostTest.php
- tests/Unit/Models/HostgroupTest.php
- tests/Unit/Models/KeyTest.php
- tests/Unit/Models/KeygroupTest.php
- tests/Unit/Models/UserTest.php
/kind feature
resolves #110 
Documentation will cover how to interact with the API
Two new dependencies has bees added.
**What else do we need to know?**
> Implements API for hosts and hostgroups management

- app/Jobs/UpdateServer.php
- app/Models/Activity.php
- app/Models/ControlRule.php
- app/Models/Host.php
- app/Models/Hostgroup.php
- app/Models/Key.php
- app/Models/Keygroup.php
- app/Models/PersonalAccessToken.php
- app/Models/User.php
- app/Presenters/ActivityPresenter.php
- app/Presenters/PersonalAccessTokenPresenter.php
> Fix Scrutinizer issues

- app/Http/Controllers/SearchController.php
- app/Http/Requests/SearchRequest.php
- app/Models/Host.php
- app/Models/Hostgroup.php
- app/Models/Key.php
- app/Models/Keygroup.php
- database/factories/HostgroupFactory.php
- database/factories/KeygroupFactory.php
- resources/lang/en/search/messages.php
- resources/views/components/search/form.blade.php
- resources/views/partials/navbar.blade.php
- resources/views/partials/sidebar.blade.php
- resources/views/search/index.blade.php
- resources/views/search/results.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/SearchControllerTest.php
> Issue 87 - Improving look and feel of Search page

- tests/ApiTestCase.php
- tests/Feature/Http/Api/ApiHostgroupsTest.php
- tests/Feature/Http/Api/ApiHostsTest.php
- tests/Feature/Http/Controllers/AuditControllerTest.php
- tests/Feature/Http/Controllers/ControlRuleControllerTest.php
- tests/Feature/Http/Controllers/HostControllerTest.php
- tests/Feature/Http/Controllers/HostgroupControllerTest.php
- tests/Feature/Http/Controllers/KeyControllerTest.php
- tests/Feature/Http/Controllers/KeygroupControllerTest.php
- tests/Feature/Http/Controllers/PersonalAccessTokenControllerTest.php
- tests/Feature/Http/Controllers/UserControllerTest.php
- tests/Feature/Policies/ControlRulePolicyTest.php
- tests/Feature/Policies/HostPolicyTest.php
- tests/Feature/Policies/HostgroupPolicyTest.php
- tests/Feature/Policies/KeyPolicyTest.php
- tests/Feature/Policies/KeygroupPolicyTest.php
- tests/Feature/Policies/UserPolicyTest.php
- tests/TestCase.php
- tests/Traits/InteractsWithPermissions.php
resolves #166 
Yes, It increase testing performance
**Before**:
Tests:  150 passed  Time:   66.59s
Tests:  150 passed  Time:   69.94s
**After**:
Tests:  150 passed  Time:   21.14s
Tests:  150 passed  Time:   21.31s
> Improve testing performance - Issue 166

- README.md
> Document default users and roles

- CHANGELOG.md
- resources/views/user/edit.blade.php
> Fix issue #235

- .github/workflows/run-tests.yml
> Change composer cache drive on tests

- docs/archetypes/default.md
- docs/config.toml
- docs/content/_index.md
- docs/content/guide/configuration.md
- docs/content/guide/getting-started.md
- docs/content/guide/introduction.md
> Add keywords, descriptions and titles to improve SEO

- composer.lock
> Fix composer lock file

- app/Actions/CreateHostAction.php
- app/Actions/CreateUserAction.php
- app/JsonApi/V1/Hostgroups/HostgroupRequest.php
- app/JsonApi/V1/Hosts/HostRequest.php
- app/Models/Host.php
- app/Presenters/HostPresenter.php
- database/factories/HostFactory.php
- database/migrations/2015_05_15_000070_create_hosts_table.php
- tests/Feature/Actions/CreateHostActionTest.php
- tests/Feature/Actions/UpdateHostActionTest.php
- tests/Feature/Http/Api/ApiHostgroupsTest.php
- tests/Feature/Http/Api/ApiHostsTest.php
- tests/Feature/Http/Controllers/ControlRuleControllerTest.php
- tests/Feature/Http/Controllers/HostControllerTest.php
- tests/Feature/Http/Controllers/HostgroupControllerTest.php
- tests/Feature/Http/Controllers/KeyControllerTest.php
- tests/Feature/Http/Controllers/KeygroupControllerTest.php
- tests/Feature/Http/Controllers/UserControllerTest.php
- tests/Feature/Models/HostTest.php
- tests/Unit/Models/HostTest.php
Increase test coverage for some missing endpoints
> Add controller tests to show objects

- docs/content/about/how-it-works.md
- docs/content/how-to/_index.md
- docs/content/how-to/prepare-hosts.md
- docs/content/using-ssham/preparing-servers.md
//kind documentation
Resolves: #88
> Adding documentation - First complete draft

- .env.example
- app/Presenters/ControlRulePresenter.php
- database/migrations/2022_05_16_144716_create_jobs_table.php
- docker-compose.yml
- tests/Feature/Presenters/ControlRulePresenterTest.php
> Add database as queue driver

- .github/workflows/run-tests.yml
- composer.lock
- docker-compose.yml
/kind bug
related to #306 
The mysql version was upgraded to 8.0, which is not compatible with Laravel 9
> Fix the mysql version (changed by mistake)

- CHANGELOG.md
- app/Http/Controllers/KeyController.php
- app/Observers/KeyObserver.php
- composer.json
- composer.lock
- database/factories/KeyFactory.php
- tests/Feature/Http/Controllers/SettingsControllerTest.php
- tests/Feature/Models/KeyTest.php
resolves #324 
resolves #323 
resolves #321 
resolves #320
> Update dependencies and fix openssh breaking changes

- CHANGELOG.md
- app/Http/Controllers/SettingsController.php
- app/Http/Requests/SettingsRequest.php
- lang/en/settings/messages.php
- resources/views/settings/edit.blade.php
- tests/Feature/Http/Controllers/SettingsControllerTest.php
/kind feature
resolves #318 
related with #165 
Remove the need of submitting a public key for the bastion host. It will be created from the submitted private key.
> Issue 318: Remove the need of submitting a public key for the bastion host

- CHANGELOG.md
- app/Http/Controllers/SettingsController.php
- app/Http/Requests/SettingsRequest.php
- database/seeders/SettingsTableSeeder.php
- resources/views/settings/edit.blade.php
- tests/Feature/Http/Controllers/SettingsControllerTest.php
Signed-off-by: pacoorozco <paco@pacoorozco.info>
related with #165
Removes the temporary dir from the Settings page
> Remove unused temporary dir from Settings page

- docker-compose.yml
> Upgrade database docker to mysql:8.0

- routes/web.php
> Use new Route::controller() method

- composer.json
- database/factories/HostgroupFactory.php
- database/factories/KeygroupFactory.php
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2015_05_15_000050_create_keygroups_table.php
- database/migrations/2015_05_15_000060_create_hostgroups_table.php
- database/migrations/2015_05_15_000070_create_hosts_table.php
- database/migrations/2015_05_15_000080_create_key_keygroups_table.php
- database/migrations/2015_05_15_000090_create_host_hostgroups_table.php
- database/migrations/2015_05_15_000100_create_hostgroup_keygroup_permissions_table.php
- database/migrations/2019_08_19_000000_create_failed_jobs_table.php
- database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
- database/migrations/2021_01_14_081141_create_activity_log_table.php
- database/migrations/2021_02_13_045654_create_settings_table.php
- database/migrations/2021_06_06_034533_create_permission_tables.php
- database/migrations/2021_06_22_072133_add_event_column_to_activity_log_table.php
- database/migrations/2021_06_22_072134_add_batch_uuid_column_to_activity_log_table.php
- database/migrations/2022_05_16_144716_create_jobs_table.php
- database/migrations/2022_10_26_153512_add_expires_at_column_to_personal_access_token_table.php
> Use l9 new methods

- composer.json
- composer.lock
- config/form-components.php
- resources/views/components/search/form.blade.php
- resources/views/host/create.blade.php
- resources/views/host/edit.blade.php
- resources/views/hostgroup/create.blade.php
- resources/views/hostgroup/edit.blade.php
- resources/views/key/create.blade.php
- resources/views/key/edit.blade.php
- resources/views/keygroup/create.blade.php
- resources/views/keygroup/edit.blade.php
- resources/views/partials/navbar.blade.php
- resources/views/rule/create.blade.php
- resources/views/settings/edit.blade.php
- resources/views/user/create.blade.php
- resources/views/user/edit.blade.php
- resources/views/user/personal_access_tokens/create.blade.php
resolves #394 
No
Yes, but removes another one
> Replace deprecated laravelcollective/html by laravel-form-components

- .github/workflows/release-version.yml
Signed-off-by: pacoorozco <paco@pacoorozco.info>
related #250
> CI: Replace deprecated create release action

- .github/workflows/release-version.yml
Signed-off-by: pacoorozco <paco@pacoorozco.info>
/kind bug
/kind feature
/kind documentation
resolves #
**What else do we need to know?**
> CI: Fix deprecation message on GHA

- .github/workflows/release-version.yml
> CI: Simplify release version GHA

- docker/ssh/Dockerfile
- docker/ssh/sshd/listen.conf
- docker/ssh/sshd/sftp.conf
- docs/content/installation/laravel-sail.md
- docs/content/installation/manual.md
- Remove SFTP chrooted configuration
- Update documentation
/kind bug
The configuration was not allowing the SFTP to be run, so it was always failing.
> fix sample ssh server docker
